"""High-level XAS analysis pipeline for DXAS.

The :class:`XAS_spec` class wraps a stack of absorption images and exposes
a fluent API for the full analysis workflow:

    image filtering → spectrum generation → normalisation →
    peak / edge detection → energy calibration
"""

from typing import Optional, Union

import numpy as np
import scipy.ndimage as nd
import skimage as sk

from .spectrum import (
    find_edge_pnts,
    interpt_spec,
    norm_spec,
    peak_finder,
    spec_cropping,
    spectrum_generate,
)

__all__ = ["XAS_spec"]


class XAS_spec:
    """DXAS image-to-spectrum analysis pipeline.

    Wraps one or more absorption images (2-D or 3-D) together with a
    spatial mask and provides chainable methods for image processing,
    spectrum extraction, normalisation, peak detection, and energy
    calibration.

    Parameters
    ----------
    imgs : ndarray, shape (..., H, W)
        Absorption image(s) (e.g. *μx* maps).  Reshaped internally to
        **(N, H, W)**.
    m : ndarray or None
        Boolean spatial mask with shape **(H, W)**.  Pixels where the mask
        is ``True`` are included in spectrum averaging.
        If ``None``, all pixels are used.

    Attributes
    ----------
    data_range : int
        Number of images in the stack (*N*).
    spec : ndarray, shape (N, 2, W)
        Pixel-space spectra generated by :meth:`spec_generate`.
    norm_spec : ndarray, shape (N, 2, interp_pts)
        Normalised and interpolated spectra set by :meth:`spec_normalize`.
    cali_spec : ndarray
        Calibrated spectra set by :meth:`generate_cali_spec`.
    edge_pnts : list
        Edge positions set by :meth:`find_edge`.
    train : list
        Feature positions (edge + peaks) used for calibration regression.

    Examples
    --------
    >>> xas = XAS_spec(mux_image, m=roi_mask)
    >>> xas.median_filtering(size=3)
    >>> xas.gaussian_filtering(sigma=0.2)
    >>> xas.spec_generate()
    >>> xas.spec_normalize(x1=100, x2=250, interp_pts=1000)
    """

    def __init__(self, imgs: np.ndarray, m: Optional[np.ndarray] = None):
        imgs = np.asarray(imgs)
        self.imgs = imgs.reshape(-1, imgs.shape[-2], imgs.shape[-1])
        self.data_range: int = self.imgs.shape[0]

        if m is None:
            self.m = np.ones(self.imgs[0].shape, dtype=bool)
        else:
            self.m = m

    # ------------------------------------------------------------------
    # Image filtering
    # ------------------------------------------------------------------

    def rotate(self, rot_angle: Union[float, list]) -> None:
        """Rotate images (and mask) in-place.

        Parameters
        ----------
        rot_angle : float or list of float
            Rotation angle(s) in degrees.  A single value is applied to
            all images; a list applies per-frame rotations.
        """
        print("Rotating images and mask…")
        rot_angle = np.atleast_1d(rot_angle)

        if len(rot_angle) == 1:
            angle = float(rot_angle[0])
            self.imgs = nd.rotate(self.imgs, angle, axes=(-2, -1), reshape=False)
            self.m = nd.rotate(self.m, angle, axes=(-2, -1), reshape=False, order=0)
            self.m[self.m < 1] = 0
            self.m = self.m.astype(bool)
        else:
            self.imgs = np.array(
                [
                    nd.rotate(self.imgs[i], float(rot_angle[i]), reshape=False)
                    for i in range(self.data_range)
                ]
            )
            m_base = self.m if self.m.ndim == 2 else self.m[0]
            self.m = np.array(
                [
                    nd.rotate(m_base, float(rot_angle[i]), reshape=False, order=0)
                    for i in range(self.data_range)
                ],
                dtype=bool,
            )

    def gaussian_filtering(self, sigma: float = 2) -> None:
        """Apply Gaussian smoothing to all images.

        Parameters
        ----------
        sigma : float
            Standard deviation of the Gaussian kernel.
        """
        self.imgs = np.array(
            [nd.gaussian_filter(self.imgs[i], sigma=sigma) for i in range(self.data_range)]
        )

    def median_filtering(self, size: int = 3, **kwargs) -> None:
        """Apply median filtering to all images.

        Parameters
        ----------
        size : int
            Kernel size (default: 3).
        """
        self.imgs = np.array(
            [
                nd.median_filter(self.imgs[i], size=size, **kwargs)
                for i in range(self.data_range)
            ]
        )

    def bilateral_filtering(self, **kwargs) -> None:
        """Apply edge-preserving bilateral denoising to all images.

        Uses ``skimage.restoration.denoise_bilateral``.  All keyword arguments
        are forwarded (e.g. ``sigma_color``, ``sigma_spatial``).
        """
        self.imgs = np.array(
            [
                sk.restoration.denoise_bilateral(
                    self.imgs[i], channel_axis=None, **kwargs
                )
                for i in range(self.data_range)
            ]
        )

    def normalize_imgs(self, imgs: Optional[np.ndarray] = None, **kwargs) -> Optional[np.ndarray]:
        """Rescale image intensities (min–max stretch).

        Parameters
        ----------
        imgs : ndarray or None
            If provided, rescale *imgs* and return the result.
            If ``None``, rescale ``self.imgs`` in-place.
        **kwargs
            Forwarded to ``skimage.exposure.rescale_intensity``.
        """
        if imgs is None:
            for i in range(self.data_range):
                self.imgs[i] = sk.exposure.rescale_intensity(self.imgs[i], **kwargs)
        else:
            for i in range(imgs.shape[0]):
                imgs[i] = sk.exposure.rescale_intensity(imgs[i], **kwargs)
            return imgs

    def show(self, alpha: float = 0.1) -> None:
        """Display images with mask overlay via pyqtgraph."""
        import pyqtgraph as pg

        pg.image(self.imgs * (alpha + self.m))

    # ------------------------------------------------------------------
    # Spectrum generation
    # ------------------------------------------------------------------

    def spec_generate(self, show: bool = True, **kwargs) -> None:
        """Generate 1-D spectra from masked images.

        For each image, the masked pixels are averaged along the spatial
        (row) axis to produce one spectrum per column (energy channel).

        Sets :attr:`spec` with shape **(N, 2, W)**.

        Parameters
        ----------
        show : bool
            Plot each spectrum as it is generated.
        **kwargs
            Forwarded to :func:`~Dispersive_XAS.spectrum.spectrum_generate`.
        """
        m = self.m
        if m.ndim == 2:
            self.spec = np.array(
                [
                    spectrum_generate(
                        np.ma.array(self.imgs[i], mask=~m),
                        show=show,
                        **kwargs,
                    )
                    for i in range(self.data_range)
                ]
            )
        else:
            self.spec = np.array(
                [
                    spectrum_generate(
                        np.ma.array(self.imgs[i], mask=~m[i]),
                        show=show,
                        **kwargs,
                    )
                    for i in range(self.data_range)
                ]
            )

    # ------------------------------------------------------------------
    # Normalisation / cropping
    # ------------------------------------------------------------------

    def spec_normalize(
        self,
        x1: float,
        x2: float,
        interp_pts: int,
        show: bool = True,
    ) -> np.ndarray:
        """Normalise and interpolate all spectra.

        Applies :func:`~Dispersive_XAS.spectrum.norm_spec` followed by
        :func:`~Dispersive_XAS.spectrum.interpt_spec` to each spectrum
        in :attr:`spec`.

        Parameters
        ----------
        x1, x2 : float
            Normalisation range (pixel units).
        interp_pts : int
            Number of interpolation points.
        show : bool
            Plot each normalised spectrum.

        Returns
        -------
        ndarray, shape (N, 2, interp_pts)
            Sets and returns :attr:`norm_spec`.
        """
        self.norm_x1 = x1
        self.norm_x2 = x2
        self.norm_spec = np.array(
            [
                interpt_spec(
                    norm_spec(self.spec[i], x1, x2, show=show),
                    pnts=interp_pts,
                )
                for i in range(self.data_range)
            ]
        )
        return self.norm_spec

    def spec_cropping(
        self, crop_E1: float, crop_E2: float, show: bool = True
    ) -> np.ndarray:
        """Crop normalised spectra to an energy range.

        Parameters
        ----------
        crop_E1, crop_E2 : float
        show : bool

        Returns
        -------
        ndarray
            Updates and returns :attr:`norm_spec`.
        """
        self.norm_spec = np.array(
            [
                spec_cropping(self.norm_spec[i], crop_E1, crop_E2, show=show)
                for i in range(self.data_range)
            ]
        )
        return self.norm_spec

    # ------------------------------------------------------------------
    # Feature extraction
    # ------------------------------------------------------------------

    def find_edge(
        self,
        y_pnts: np.ndarray,
        x1: float,
        x2: float,
        show: bool = True,
    ) -> list:
        """Find absorption edge positions across all normalised spectra.

        Parameters
        ----------
        y_pnts : ndarray
            Target intensity fractions (e.g. ``[0.2, 0.7]``).
        x1, x2 : float
            Energy window for the edge search.
        show : bool

        Returns
        -------
        list of ndarray
            Sets and returns :attr:`edge_pnts`.
        """
        self.edge_pnts = [
            find_edge_pnts(self.norm_spec[i], y_pnts, x1, x2, show=show)
            for i in range(self.data_range)
        ]
        return self.edge_pnts

    def find_peaks(
        self,
        x1: float,
        x2: float,
        peak_n: int,
        show: bool = True,
        filtering: bool = True,
        window_length: int = 3,
        polyorder: int = 2,
        **kwargs,
    ) -> None:
        """Find spectral peaks and combine with edge points for calibration.

        Sets :attr:`peaks` and :attr:`train`.

        Parameters
        ----------
        x1, x2 : float
            Energy interval for the peak search.
        peak_n : int
            Number of peaks to extract.
        show : bool
        filtering : bool
            Apply Savitzky–Golay smoothing before detection.
        window_length : int
            Savitzky–Golay window length.
        polyorder : int
            Savitzky–Golay polynomial order.
        **kwargs
            Extra arguments forwarded to
            :func:`~Dispersive_XAS.spectrum.peak_finder`.
        """
        self.peaks = [
            peak_finder(
                self.norm_spec[i],
                x1,
                x2,
                peak_n=peak_n,
                show=show,
                filtering=filtering,
                window_length=window_length,
                polyorder=polyorder,
                **kwargs,
            )
            for i in range(self.data_range)
        ]
        # Prepend edge point to the peak positions → calibration training set
        self.train = [
            np.insert(self.peaks[i][1], 0, self.edge_pnts[i])
            for i in range(self.data_range)
        ]

    # ------------------------------------------------------------------
    # Calibration application
    # ------------------------------------------------------------------

    def generate_cali_spec(self, fits: list) -> np.ndarray:
        """Apply fitted calibration objects to update the energy axis.

        Parameters
        ----------
        fits : list of :class:`~Dispersive_XAS.calibration.EDXAS_Calibrate`
            One calibration object per spectrum in the stack.

        Returns
        -------
        ndarray
            Sets and returns :attr:`cali_spec`.
        """
        self.cali_spec = self.norm_spec.copy()
        for i in range(len(fits)):
            self.cali_spec[i][0] = fits[i].sample_spec(self.norm_spec[i])[:, 1]
        return self.cali_spec
